FROM risingstack/alpine:3.4-v6.11.2-4.5.2

WORKDIR /opt/app

RUN npm install -g yarn

ADD frontend/package.json /tmp/package.json
RUN cd /tmp && yarn
RUN mkdir -p /opt/app && cd /opt/app && ln -s /tmp/node_modules

copy frontend/ .

EXPOSE 3000

CMD ["yarn", "start"]